project:
  type: website

website:
  title: "US Traffic Accidents Analysis"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: sources.qmd
        text: sources
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



